services:
    offer.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        tags: [ 'api_platform.filter' ]
    offer.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [ { id: ~, name: ~ } ]
        tags: [ 'api_platform.filter' ]